"""co2_scrubber.py — Mars Habitat CO₂ Removal & Sabatier Recycling System.

The breath trap.  Six crew breathe in O₂ and breathe out CO₂.  In a
sealed habitat on Mars, CO₂ accumulates relentlessly:

  0.04%  — Earth ambient (400 ppm)
  0.5%   — drowsiness, headaches begin (ISS operational target)
  2.0%   — impaired cognitive function
  5.0%   — incapacitation, panic, loss of consciousness
  10.0%  — death within minutes

Without active CO₂ removal, a 6-person crew in a 500 m³ habitat
reaches dangerous levels in ~12 hours.  This is not optional.

Treatment pipeline (three-stage, ISS-heritage)
-----------------------------------------------
1. **Zeolite molecular sieve (CDRA-type)** — Zeolite 13X adsorbs CO₂
   at ambient temperature.  Regenerated by heating to 250°C under
   vacuum (desorbed CO₂ is captured, not vented).  Two beds alternate:
   one adsorbs while the other regenerates.  Langmuir isotherm:
     q = q_max · K·P / (1 + K·P)

2. **Sabatier reactor** — Captured CO₂ reacts with H₂ from the
   electrolyzer:  CO₂ + 4H₂ → CH₄ + 2H₂O (ΔH = −165 kJ/mol).
   Recovers water (feeds back to electrolysis).  Methane is either
   vented or stored for fuel production.

3. **LiOH emergency canisters** — One-use backup:
     2LiOH + CO₂ → Li₂CO₃ + H₂O
   Finite supply.  Used only when primary system is down.

Conservation laws
-----------------
- CO₂ generated = CO₂ adsorbed + CO₂ in habitat air (mass balance)
- Sabatier: 1 mol CO₂ + 4 mol H₂ → 1 mol CH₄ + 2 mol H₂O (exact)
- LiOH: 2 mol LiOH + 1 mol CO₂ → 1 mol Li₂CO₃ + 1 mol H₂O
- CO₂ partial pressure ≥ 0, ≤ habitat total pressure
- Energy consumed = zeolite regen + Sabatier heating + pumps

Reference:
  - ISS CDRA: 4-bed molecular sieve, removes ~6 kg CO₂/day (6 crew)
  - Human CO₂ output: ~1.0 kg/person/day at rest, ~1.4 kg active
  - Zeolite 13X capacity: ~0.18 kg CO₂/kg zeolite at 0.5 kPa, 25°C
  - Sabatier ΔH = −165.0 kJ/mol (exothermic, self-sustaining once lit)
  - LiOH capacity: 0.92 kg CO₂ per kg LiOH
  - ISS CO₂ setpoint: 0.5% (5.3 mmHg), alarm at 0.7%

One tick = one sol.  Mass in kg, pressure in kPa, energy in kWh.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import List, Tuple


# ── Physical & chemical constants ───────────────────────────────────

CO2_MOLAR_MASS = 44.01       # g/mol
H2_MOLAR_MASS = 2.016        # g/mol
CH4_MOLAR_MASS = 16.04       # g/mol
H2O_MOLAR_MASS = 18.015      # g/mol
LIOH_MOLAR_MASS = 23.95      # g/mol
LI2CO3_MOLAR_MASS = 73.89    # g/mol

# Sabatier stoichiometry: CO₂ + 4H₂ → CH₄ + 2H₂O
SABATIER_H2_PER_CO2 = 4.0 * H2_MOLAR_MASS / CO2_MOLAR_MASS   # kg H₂ / kg CO₂
SABATIER_CH4_PER_CO2 = CH4_MOLAR_MASS / CO2_MOLAR_MASS        # kg CH₄ / kg CO₂
SABATIER_H2O_PER_CO2 = 2.0 * H2O_MOLAR_MASS / CO2_MOLAR_MASS # kg H₂O / kg CO₂
SABATIER_DELTA_H_KJ_MOL = -165.0  # exothermic

# LiOH stoichiometry: 2LiOH + CO₂ → Li₂CO₃ + H₂O
LIOH_PER_CO2 = 2.0 * LIOH_MOLAR_MASS / CO2_MOLAR_MASS  # kg LiOH / kg CO₂
LIOH_CO2_CAPACITY = CO2_MOLAR_MASS / (2.0 * LIOH_MOLAR_MASS)  # kg CO₂ / kg LiOH

# Crew respiration
CO2_PER_PERSON_KG_SOL = 1.0       # kg CO₂ per person per sol (resting avg)
CO2_ACTIVE_MULTIPLIER = 1.4       # during EVA or exercise

# Habitat parameters
HABITAT_VOLUME_M3 = 500.0
HABITAT_PRESSURE_KPA = 70.0
CO2_AMBIENT_FRACTION = 0.0004     # Earth: 400 ppm
CO2_TARGET_FRACTION = 0.005       # ISS target: 0.5%
CO2_WARNING_FRACTION = 0.007      # ISS alarm: 0.7%
CO2_DANGER_FRACTION = 0.020       # cognitive impairment
CO2_CRITICAL_FRACTION = 0.050     # incapacitation

# Partial pressures
CO2_TARGET_KPA = HABITAT_PRESSURE_KPA * CO2_TARGET_FRACTION   # 0.35 kPa
CO2_WARNING_KPA = HABITAT_PRESSURE_KPA * CO2_WARNING_FRACTION # 0.49 kPa
CO2_DANGER_KPA = HABITAT_PRESSURE_KPA * CO2_DANGER_FRACTION   # 1.4 kPa
CO2_CRITICAL_KPA = HABITAT_PRESSURE_KPA * CO2_CRITICAL_FRACTION  # 3.5 kPa

# Air density at hab conditions (~70 kPa, 20°C)
# ρ = P·M / (R·T) ≈ 70000 × 0.029 / (8.314 × 293) ≈ 0.833 kg/m³
HAB_AIR_DENSITY = 0.833

# ── Zeolite molecular sieve parameters ──────────────────────────────

ZEOLITE_BED_MASS_KG = 100.0        # kg of zeolite 13X per bed (Mars-scale)
ZEOLITE_CAPACITY_KG_CO2_PER_KG = 0.18  # at ~0.5 kPa CO₂, 25°C
ZEOLITE_TOTAL_CAPACITY_KG = ZEOLITE_BED_MASS_KG * ZEOLITE_CAPACITY_KG_CO2_PER_KG
ZEOLITE_REGEN_TEMP_C = 250.0       # desorption temperature
ZEOLITE_REGEN_ENERGY_KWH = 3.0     # energy per regeneration cycle
ZEOLITE_CYCLE_HOURS = 2.5          # one bed cycle: 2.5h adsorb, 2.5h regen
ZEOLITE_CYCLES_PER_SOL = 24.65 / ZEOLITE_CYCLE_HOURS  # ~6 cycles/sol
ZEOLITE_EFFICIENCY = 0.92          # fraction of capacity actually used
ZEOLITE_DEGRADATION_PER_CYCLE = 0.0001  # 0.01% capacity loss per cycle

# Langmuir adsorption parameters
LANGMUIR_Q_MAX = 0.22             # mol CO₂ per kg zeolite at saturation
LANGMUIR_K = 8.0                  # kPa⁻¹ (affinity constant at 25°C)

# ── Sabatier reactor parameters ─────────────────────────────────────

SABATIER_CONVERSION = 0.95         # CO₂ conversion efficiency
SABATIER_STARTUP_KWH = 1.5        # energy to heat catalyst to 300°C
SABATIER_OPERATING_TEMP_C = 300.0  # optimal catalyst temperature
SABATIER_MIN_CO2_KG = 0.5         # minimum batch size to run reactor

# ── LiOH emergency parameters ──────────────────────────────────────

LIOH_CANISTER_KG = 2.0            # LiOH per canister
LIOH_INITIAL_CANISTERS = 50       # emergency stockpile
LIOH_CO2_PER_CANISTER = LIOH_CANISTER_KG * LIOH_CO2_CAPACITY

# ── Energy ──────────────────────────────────────────────────────────

FAN_PUMP_KWH_SOL = 1.0            # air circulation fans per sol


# ── Data structures ─────────────────────────────────────────────────

@dataclass
class ScrubberState:
    """Full state of the CO₂ removal system."""

    # Habitat atmosphere
    co2_kpa: float = CO2_TARGET_KPA
    co2_fraction: float = CO2_TARGET_FRACTION

    # Zeolite sieve
    zeolite_capacity_kg: float = ZEOLITE_TOTAL_CAPACITY_KG
    zeolite_loaded_kg: float = 0.0
    zeolite_cycles_total: int = 0

    # Sabatier reactor
    sabatier_co2_buffer_kg: float = 0.0   # CO₂ waiting for processing
    sabatier_active: bool = True

    # LiOH emergency
    lioh_canisters: int = LIOH_INITIAL_CANISTERS
    lioh_active: bool = False

    # Cumulative totals
    total_co2_generated_kg: float = 0.0
    total_co2_scrubbed_kg: float = 0.0
    total_co2_sabatier_kg: float = 0.0
    total_ch4_produced_kg: float = 0.0
    total_h2o_recovered_kg: float = 0.0
    total_h2_consumed_kg: float = 0.0
    total_lioh_used_canisters: int = 0
    total_energy_kwh: float = 0.0

    # Operational
    sols_running: int = 0
    crew_count: int = 6
    alert: str = "nominal"

    def __post_init__(self) -> None:
        """Clamp to physical bounds."""
        self.co2_kpa = max(0.0, min(HABITAT_PRESSURE_KPA, self.co2_kpa))
        self.co2_fraction = max(0.0, min(1.0, self.co2_fraction))
        self.zeolite_loaded_kg = max(0.0, min(self.zeolite_capacity_kg,
                                               self.zeolite_loaded_kg))
        self.sabatier_co2_buffer_kg = max(0.0, self.sabatier_co2_buffer_kg)
        self.lioh_canisters = max(0, self.lioh_canisters)
        self.crew_count = max(0, min(20, self.crew_count))


@dataclass
class ScrubberTickResult:
    """Result of one sol of CO₂ scrubbing."""
    co2_generated_kg: float = 0.0
    co2_zeolite_kg: float = 0.0
    co2_sabatier_kg: float = 0.0
    co2_lioh_kg: float = 0.0
    ch4_produced_kg: float = 0.0
    h2o_recovered_kg: float = 0.0
    h2_consumed_kg: float = 0.0
    lioh_canisters_used: int = 0
    co2_kpa: float = 0.0
    co2_fraction: float = 0.0
    energy_kwh: float = 0.0
    alert: str = "nominal"


# ── Pure chemistry / physics functions ──────────────────────────────

def co2_generation_kg(crew: int, active_fraction: float = 0.3) -> float:
    """CO₂ generated by crew in one sol (kg).

    Parameters
    ----------
    crew : int
        Number of crew members.
    active_fraction : float
        Fraction of sol spent in active work (EVA, exercise).
    """
    crew = max(0, crew)
    active_fraction = max(0.0, min(1.0, active_fraction))
    rest_output = CO2_PER_PERSON_KG_SOL * (1.0 - active_fraction)
    active_output = CO2_PER_PERSON_KG_SOL * CO2_ACTIVE_MULTIPLIER * active_fraction
    return crew * (rest_output + active_output)


def co2_kpa_from_mass(co2_mass_kg: float, volume_m3: float = HABITAT_VOLUME_M3,
                      temp_k: float = 293.0) -> float:
    """Convert CO₂ mass (kg) to partial pressure (kPa).

    P = m·R·T / (M·V), where M = CO₂ molar mass.
    """
    co2_mass_kg = max(0.0, co2_mass_kg)
    volume_m3 = max(0.01, volume_m3)
    pressure_pa = (co2_mass_kg * 1000.0 * 8.314 * temp_k) / (CO2_MOLAR_MASS * volume_m3)
    return max(0.0, pressure_pa / 1000.0)


def co2_mass_from_kpa(co2_kpa: float, volume_m3: float = HABITAT_VOLUME_M3,
                      temp_k: float = 293.0) -> float:
    """Convert CO₂ partial pressure (kPa) to mass (kg)."""
    co2_kpa = max(0.0, co2_kpa)
    volume_m3 = max(0.01, volume_m3)
    mass_g = (co2_kpa * 1000.0 * CO2_MOLAR_MASS * volume_m3) / (8.314 * temp_k)
    return max(0.0, mass_g / 1000.0)


def langmuir_loading(pressure_kpa: float, q_max: float = LANGMUIR_Q_MAX,
                     k: float = LANGMUIR_K) -> float:
    """Zeolite CO₂ loading via Langmuir isotherm (mol/kg zeolite).

    q = q_max · K·P / (1 + K·P)
    """
    pressure_kpa = max(0.0, pressure_kpa)
    return q_max * k * pressure_kpa / (1.0 + k * pressure_kpa)


def zeolite_removal_kg(co2_kpa: float, bed_mass_kg: float,
                       current_load_kg: float, capacity_kg: float,
                       efficiency: float = ZEOLITE_EFFICIENCY) -> float:
    """CO₂ removed by zeolite bed in one cycle (kg).

    Based on Langmuir equilibrium loading minus current load.
    """
    bed_mass_kg = max(0.0, bed_mass_kg)
    current_load_kg = max(0.0, current_load_kg)
    capacity_kg = max(0.001, capacity_kg)
    efficiency = max(0.0, min(1.0, efficiency))

    # Equilibrium loading
    loading_mol_per_kg = langmuir_loading(co2_kpa)
    eq_load_kg = loading_mol_per_kg * (CO2_MOLAR_MASS / 1000.0) * bed_mass_kg

    # Available capacity
    space = max(0.0, capacity_kg - current_load_kg)
    removal = min(eq_load_kg * efficiency, space)
    return max(0.0, removal)


def sabatier_products(co2_kg: float,
                      conversion: float = SABATIER_CONVERSION) -> Tuple[float, float, float, float]:
    """Products from Sabatier reaction.

    CO₂ + 4H₂ → CH₄ + 2H₂O

    Returns
    -------
    tuple[float, float, float, float]
        (co2_consumed_kg, h2_consumed_kg, ch4_produced_kg, h2o_produced_kg)
    """
    co2_kg = max(0.0, co2_kg)
    conversion = max(0.0, min(1.0, conversion))

    co2_consumed = co2_kg * conversion
    h2_consumed = co2_consumed * SABATIER_H2_PER_CO2
    ch4_produced = co2_consumed * SABATIER_CH4_PER_CO2
    h2o_produced = co2_consumed * SABATIER_H2O_PER_CO2

    return (co2_consumed, h2_consumed, ch4_produced, h2o_produced)


def sabatier_energy_kwh(co2_kg: float) -> float:
    """Net energy for Sabatier reactor operation (kWh).

    Reaction is exothermic (−165 kJ/mol), but startup and pumping
    require energy.  Net: startup cost amortized over batch.
    """
    if co2_kg < SABATIER_MIN_CO2_KG:
        return 0.0
    return SABATIER_STARTUP_KWH


def lioh_removal_kg(canisters: int) -> float:
    """CO₂ removed by LiOH canisters (kg)."""
    return max(0, canisters) * LIOH_CO2_PER_CANISTER


def assess_alert(co2_fraction: float, zeolite_health: float,
                 lioh_canisters: int) -> str:
    """Determine system alert level."""
    if co2_fraction >= CO2_CRITICAL_FRACTION:
        return "critical"
    if co2_fraction >= CO2_DANGER_FRACTION:
        return "danger"
    if co2_fraction >= CO2_WARNING_FRACTION or lioh_canisters <= 5:
        return "warning"
    if zeolite_health < 0.5:
        return "warning"
    return "nominal"


def zeolite_health(capacity_kg: float) -> float:
    """Zeolite bed health as fraction of original capacity."""
    original = ZEOLITE_BED_MASS_KG * ZEOLITE_CAPACITY_KG_CO2_PER_KG
    if original <= 0:
        return 0.0
    return max(0.0, min(1.0, capacity_kg / original))


# ── Tick function ───────────────────────────────────────────────────

def tick_scrubber(state: ScrubberState,
                  h2_available_kg: float = 5.0,
                  power_available_kwh: float = 30.0,
                  active_fraction: float = 0.3) -> Tuple[ScrubberState, ScrubberTickResult]:
    """Advance CO₂ scrubber by one sol.

    Parameters
    ----------
    state : ScrubberState
        Current system state.
    h2_available_kg : float
        Hydrogen available from electrolyzer for Sabatier.
    power_available_kwh : float
        Energy budget for this sol.
    active_fraction : float
        Fraction of sol crew spends in active work.

    Returns
    -------
    tuple[ScrubberState, ScrubberTickResult]
    """
    result = ScrubberTickResult()
    energy_used = FAN_PUMP_KWH_SOL

    # ── CO₂ generation from crew ────────────────────────────────────
    generated = co2_generation_kg(state.crew_count, active_fraction)
    state.total_co2_generated_kg += generated
    result.co2_generated_kg = generated

    # Add to habitat atmosphere
    current_co2_mass = co2_mass_from_kpa(state.co2_kpa)
    current_co2_mass += generated

    # ── Stage 1: Zeolite molecular sieve ────────────────────────────
    cycles = int(ZEOLITE_CYCLES_PER_SOL)
    total_zeolite_removed = 0.0
    regen_energy = 0.0

    for _ in range(cycles):
        co2_now_kpa = co2_kpa_from_mass(current_co2_mass)
        removed = zeolite_removal_kg(
            co2_now_kpa, ZEOLITE_BED_MASS_KG,
            state.zeolite_loaded_kg, state.zeolite_capacity_kg,
        )
        # Power-limit the cycle
        cycle_energy = ZEOLITE_REGEN_ENERGY_KWH
        if energy_used + regen_energy + cycle_energy > power_available_kwh:
            break

        state.zeolite_loaded_kg += removed
        current_co2_mass = max(0.0, current_co2_mass - removed)
        total_zeolite_removed += removed
        regen_energy += cycle_energy

        # Regenerate: desorb CO₂ into buffer
        if state.zeolite_loaded_kg > state.zeolite_capacity_kg * 0.8:
            desorbed = state.zeolite_loaded_kg * 0.95
            state.zeolite_loaded_kg -= desorbed
            state.sabatier_co2_buffer_kg += desorbed
            state.zeolite_cycles_total += 1
            # Degradation
            state.zeolite_capacity_kg *= (1.0 - ZEOLITE_DEGRADATION_PER_CYCLE)
            state.zeolite_capacity_kg = max(0.1, state.zeolite_capacity_kg)

    energy_used += regen_energy
    result.co2_zeolite_kg = total_zeolite_removed
    state.total_co2_scrubbed_kg += total_zeolite_removed

    # ── Stage 2: Sabatier reactor ───────────────────────────────────
    co2_for_sabatier = state.sabatier_co2_buffer_kg
    sab_co2 = 0.0
    sab_h2 = 0.0
    sab_ch4 = 0.0
    sab_h2o = 0.0

    if (state.sabatier_active and co2_for_sabatier >= SABATIER_MIN_CO2_KG
            and h2_available_kg > 0):
        sab_energy = sabatier_energy_kwh(co2_for_sabatier)
        if energy_used + sab_energy <= power_available_kwh:
            # Limit by H₂ availability
            max_co2_by_h2 = h2_available_kg / max(0.001, SABATIER_H2_PER_CO2)
            co2_to_process = min(co2_for_sabatier, max_co2_by_h2)

            sab_co2, sab_h2, sab_ch4, sab_h2o = sabatier_products(co2_to_process)
            state.sabatier_co2_buffer_kg -= sab_co2
            state.sabatier_co2_buffer_kg = max(0.0, state.sabatier_co2_buffer_kg)
            state.total_co2_sabatier_kg += sab_co2
            state.total_ch4_produced_kg += sab_ch4
            state.total_h2o_recovered_kg += sab_h2o
            state.total_h2_consumed_kg += sab_h2
            energy_used += sab_energy

    result.co2_sabatier_kg = sab_co2
    result.ch4_produced_kg = sab_ch4
    result.h2o_recovered_kg = sab_h2o
    result.h2_consumed_kg = sab_h2

    # ── Stage 3: LiOH emergency (if CO₂ still too high) ────────────
    co2_kpa_now = co2_kpa_from_mass(current_co2_mass)
    lioh_used = 0

    if co2_kpa_now > CO2_WARNING_KPA and state.lioh_canisters > 0:
        state.lioh_active = True
        # Use canisters until safe or exhausted
        while co2_kpa_now > CO2_TARGET_KPA and state.lioh_canisters > 0:
            removed_by_lioh = LIOH_CO2_PER_CANISTER
            current_co2_mass = max(0.0, current_co2_mass - removed_by_lioh)
            co2_kpa_now = co2_kpa_from_mass(current_co2_mass)
            state.lioh_canisters -= 1
            state.total_lioh_used_canisters += 1
            lioh_used += 1
            state.total_co2_scrubbed_kg += removed_by_lioh
    else:
        state.lioh_active = False

    result.co2_lioh_kg = lioh_used * LIOH_CO2_PER_CANISTER
    result.lioh_canisters_used = lioh_used

    # ── Update atmosphere state ─────────────────────────────────────
    state.co2_kpa = co2_kpa_from_mass(current_co2_mass)
    state.co2_fraction = state.co2_kpa / max(0.01, HABITAT_PRESSURE_KPA)
    state.co2_fraction = max(0.0, min(1.0, state.co2_fraction))

    result.co2_kpa = state.co2_kpa
    result.co2_fraction = state.co2_fraction

    # ── Energy & status ─────────────────────────────────────────────
    state.total_energy_kwh += energy_used
    result.energy_kwh = energy_used

    z_health = zeolite_health(state.zeolite_capacity_kg)
    alert = assess_alert(state.co2_fraction, z_health, state.lioh_canisters)
    result.alert = alert
    state.alert = alert
    state.sols_running += 1

    return state, result


# ── Factory ─────────────────────────────────────────────────────────

def create_scrubber(crew: int = 6,
                    co2_kpa: float = CO2_TARGET_KPA) -> ScrubberState:
    """Create a CO₂ scrubber for the given crew size."""
    return ScrubberState(
        crew_count=max(0, min(20, crew)),
        co2_kpa=max(0.0, min(HABITAT_PRESSURE_KPA, co2_kpa)),
        co2_fraction=max(0.0, co2_kpa / HABITAT_PRESSURE_KPA),
    )
