"""
life_support.py — Mars habitat atmospheric management.

Models O₂ generation via water electrolysis, CO₂ scrubbing,
atmospheric pressure regulation, and crew metabolic gas exchange.

Physical references:
  - Human O₂ consumption: ~0.84 kg/person/day (NASA ECLSS)
  - Human CO₂ production: ~1.00 kg/person/day (NASA ECLSS)
  - Water electrolysis: 2H₂O → 2H₂ + O₂
    - 1 kg O₂ requires 1.125 kg H₂O
    - Energy: ~5.0 kWh per kg O₂ (PEM electrolyser at Mars pressure)
  - Sabatier CO₂ scrubbing: CO₂ + 4H₂ → CH₄ + 2H₂O
    - Recovers ~50% of water from CO₂ (closed-loop bonus)
    - Energy: ~1.2 kWh per kg CO₂ processed
  - Habitat target atmosphere:
    - O₂ partial pressure: 21.3 kPa (Earth-normal)
    - CO₂ partial pressure: <0.5 kPa (NASA 1000-day limit)
    - Total pressure: 70 kPa (reduced-pressure mixed gas)

One tick = one sol. Mass in kg, energy in kWh, pressure in kPa.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field


# ---------------------------------------------------------------------------
# Physical constants
# ---------------------------------------------------------------------------

O2_KG_PER_PERSON_SOL = 0.84          # NASA ECLSS baseline
CO2_KG_PER_PERSON_SOL = 1.00         # metabolic CO₂ output
WATER_PER_KG_O2 = 1.125              # stoichiometric H₂O→O₂
ELECTROLYSIS_KWH_PER_KG_O2 = 5.0     # PEM electrolyser energy
SABATIER_KWH_PER_KG_CO2 = 1.2        # Sabatier reactor energy
SABATIER_WATER_RECOVERY = 0.50        # fraction of water recovered from CO₂
TARGET_O2_KPA = 21.3                  # Earth-normal O₂ partial pressure
MAX_CO2_KPA = 0.5                     # NASA safe limit for long duration
TARGET_TOTAL_KPA = 70.0               # reduced-pressure habitat
LEAK_RATE_FRACTION = 0.001            # 0.1% atmospheric loss per sol (seals)
MIN_O2_EMERGENCY_KPA = 16.0           # hypoxia threshold


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class Atmosphere:
    """Habitat atmospheric state.

    Attributes:
        o2_kpa: oxygen partial pressure (kPa)
        co2_kpa: carbon dioxide partial pressure (kPa)
        total_kpa: total habitat pressure (kPa)
        o2_reserve_kg: stored liquid O₂ reserve
        co2_scrubbed_kg: cumulative CO₂ removed
    """
    o2_kpa: float = TARGET_O2_KPA
    co2_kpa: float = 0.04             # start near Earth ambient
    total_kpa: float = TARGET_TOTAL_KPA
    o2_reserve_kg: float = 500.0      # emergency buffer
    co2_scrubbed_kg: float = 0.0

    def __post_init__(self) -> None:
        self.o2_kpa = max(0.0, self.o2_kpa)
        self.co2_kpa = max(0.0, self.co2_kpa)
        self.total_kpa = max(0.0, self.total_kpa)
        self.o2_reserve_kg = max(0.0, self.o2_reserve_kg)


@dataclass
class LifeSupportStatus:
    """Status report from one sol of life support operation.

    Attributes:
        o2_produced_kg: O₂ generated by electrolysis
        co2_removed_kg: CO₂ scrubbed by Sabatier reactor
        water_consumed_kg: net water used (electrolysis - Sabatier recovery)
        power_consumed_kwh: total power for O₂ gen + CO₂ scrubbing
        water_recovered_kg: water reclaimed via Sabatier
        o2_deficit_kg: shortfall if power/water insufficient
        emergency: True if O₂ dropped below hypoxia threshold
    """
    o2_produced_kg: float = 0.0
    co2_removed_kg: float = 0.0
    water_consumed_kg: float = 0.0
    power_consumed_kwh: float = 0.0
    water_recovered_kg: float = 0.0
    o2_deficit_kg: float = 0.0
    emergency: bool = False


# ---------------------------------------------------------------------------
# Core functions
# ---------------------------------------------------------------------------

def crew_o2_demand(population: int) -> float:
    """Total O₂ demand for the crew (kg/sol)."""
    return max(0, population) * O2_KG_PER_PERSON_SOL


def crew_co2_output(population: int) -> float:
    """Total CO₂ produced by the crew (kg/sol)."""
    return max(0, population) * CO2_KG_PER_PERSON_SOL


def electrolysis_water_needed(o2_kg: float) -> float:
    """Water required to produce a given mass of O₂ (kg)."""
    return max(0.0, o2_kg) * WATER_PER_KG_O2


def electrolysis_power_needed(o2_kg: float) -> float:
    """Power required to produce a given mass of O₂ (kWh)."""
    return max(0.0, o2_kg) * ELECTROLYSIS_KWH_PER_KG_O2


def sabatier_power_needed(co2_kg: float) -> float:
    """Power required to scrub a given mass of CO₂ (kWh)."""
    return max(0.0, co2_kg) * SABATIER_KWH_PER_KG_CO2


def sabatier_water_recovery_kg(co2_kg: float) -> float:
    """Water recovered from Sabatier CO₂ processing (kg).

    Sabatier: CO₂ + 4H₂ → CH₄ + 2H₂O.
    Recovery ratio accounts for real-world inefficiency.
    """
    return max(0.0, co2_kg) * SABATIER_WATER_RECOVERY


def atmospheric_leak(atmo: Atmosphere) -> float:
    """O₂ lost to microleaks per sol (kPa).

    Real habitats lose ~0.1% of atmosphere per sol through seals.
    """
    return atmo.o2_kpa * LEAK_RATE_FRACTION


def o2_pressure_from_mass(o2_kg: float, habitat_volume_m3: float) -> float:
    """Convert O₂ mass change to partial pressure change (kPa).

    Ideal gas law: ΔP = nRT/V.
    O₂ molar mass = 32 g/mol, R = 8.314 J/(mol·K), T ≈ 293 K.
    ΔP (Pa) = (m/0.032) × 8.314 × 293 / V → convert to kPa.
    """
    if habitat_volume_m3 <= 0:
        return 0.0
    moles = o2_kg / 0.032
    delta_pa = moles * 8.314 * 293.0 / habitat_volume_m3
    return delta_pa / 1000.0


def co2_pressure_from_mass(co2_kg: float, habitat_volume_m3: float) -> float:
    """Convert CO₂ mass change to partial pressure change (kPa).

    CO₂ molar mass = 44 g/mol.
    """
    if habitat_volume_m3 <= 0:
        return 0.0
    moles = co2_kg / 0.044
    delta_pa = moles * 8.314 * 293.0 / habitat_volume_m3
    return delta_pa / 1000.0


def tick_life_support(
    atmo: Atmosphere,
    population: int,
    power_available_kwh: float,
    water_available_kg: float,
    habitat_volume_m3: float = 500.0,
) -> LifeSupportStatus:
    """Advance life support by one sol.

    Priority order:
      1. Generate O₂ via electrolysis (crew survival)
      2. Scrub CO₂ via Sabatier (prevents CO₂ poisoning)
      3. Replenish reserves if surplus power/water

    Args:
        atmo: habitat atmosphere (mutated in place)
        population: number of crew members
        power_available_kwh: power budget for life support
        water_available_kg: water budget for electrolysis
        habitat_volume_m3: pressurised habitat volume

    Returns:
        LifeSupportStatus for this sol.
    """
    status = LifeSupportStatus()
    population = max(0, population)

    if population == 0:
        # Apply leak only, no metabolic exchange
        leak = atmospheric_leak(atmo)
        atmo.o2_kpa -= leak
        atmo.o2_kpa = max(0.0, atmo.o2_kpa)
        return status

    # --- Step 1: Crew metabolism ---
    o2_demand = crew_o2_demand(population)
    co2_produced = crew_co2_output(population)

    # --- Step 2: O₂ generation (power + water limited) ---
    water_needed = electrolysis_water_needed(o2_demand)
    power_needed = electrolysis_power_needed(o2_demand)

    water_fraction = min(1.0, water_available_kg / water_needed) if water_needed > 0 else 1.0
    power_fraction = min(1.0, power_available_kwh / power_needed) if power_needed > 0 else 1.0
    production_fraction = min(water_fraction, power_fraction)

    o2_produced = o2_demand * production_fraction
    water_used_electrolysis = electrolysis_water_needed(o2_produced)
    power_used_electrolysis = electrolysis_power_needed(o2_produced)

    remaining_power = power_available_kwh - power_used_electrolysis
    remaining_water = water_available_kg - water_used_electrolysis

    status.o2_produced_kg = o2_produced

    # O₂ deficit — may need to dip into reserves
    o2_deficit = o2_demand - o2_produced
    if o2_deficit > 0 and atmo.o2_reserve_kg > 0:
        from_reserve = min(o2_deficit, atmo.o2_reserve_kg)
        atmo.o2_reserve_kg -= from_reserve
        o2_deficit -= from_reserve
        o2_produced += from_reserve  # effective O₂ available

    status.o2_deficit_kg = max(0.0, o2_demand - o2_produced)

    # --- Step 3: CO₂ scrubbing (Sabatier, power limited) ---
    scrub_power = sabatier_power_needed(co2_produced)
    if remaining_power >= scrub_power:
        co2_removed = co2_produced
        power_used_sabatier = scrub_power
    else:
        scrub_fraction = remaining_power / scrub_power if scrub_power > 0 else 0.0
        co2_removed = co2_produced * scrub_fraction
        power_used_sabatier = remaining_power

    water_recovered = sabatier_water_recovery_kg(co2_removed)
    status.co2_removed_kg = co2_removed
    status.water_recovered_kg = water_recovered
    status.water_consumed_kg = max(0.0, water_used_electrolysis - water_recovered)
    status.power_consumed_kwh = power_used_electrolysis + power_used_sabatier

    # --- Step 4: Update atmosphere ---
    # O₂: produced - consumed
    net_o2_kg = o2_produced - o2_demand
    atmo.o2_kpa += o2_pressure_from_mass(net_o2_kg, habitat_volume_m3)

    # CO₂: produced by crew - scrubbed
    net_co2_kg = co2_produced - co2_removed
    atmo.co2_kpa += co2_pressure_from_mass(net_co2_kg, habitat_volume_m3)

    # Atmospheric leak
    leak = atmospheric_leak(atmo)
    atmo.o2_kpa -= leak

    # Clamp
    atmo.o2_kpa = max(0.0, atmo.o2_kpa)
    atmo.co2_kpa = max(0.0, atmo.co2_kpa)
    atmo.co2_scrubbed_kg += co2_removed

    # Emergency check
    if atmo.o2_kpa < MIN_O2_EMERGENCY_KPA:
        status.emergency = True

    return status
